In [112]:
pd.options.display.max_rows = 4000

In [4]:
from tabula import read_pdf
import tabula
import pandas as pd
import re
import math

In [11]:
def pdf_transform_v1(start, end, pdf):
    
    unit = []
    station = []
    line = []
    availability = []
    comment = ''
    comments = []
    
    df = tabula.read_pdf(pdf, pages=list(range(start, end + 1)))
    df.dropna(how = 'all', inplace = True)
    df.reset_index(inplace = True, drop = True)
    
    df_revision = df.copy()
    df_null = df.isna()
    
    df_revision.replace(to_replace=[r"\\t|\\n|\\r", "\t|\n|\r"], value=[" "," "], regex=True, inplace=True)
    
    df_comment = pd.DataFrame(
        {'full comment': df['Unnamed: 3'].str.contains('^(Th).*$'),
         'starts percent': df['Unnamed: 3'].str.contains('\d{1,2}\.\d{2}\%'),
         'continued comment': df['Unnamed: 3'].str.contains('^[a-zA-SU-Z]*[\s]'),
         'all caps': df['Unnamed: 3'].str.contains('^[^a-z]*$'),
         'no spaces': df['Unnamed: 3'].str.contains('^[^\s]*$'),
        })

    for i in range(len(df)):
        try:
            if math.isnan(float(df.iloc[i][1])) is True:
                pass
        except:
            if df.iloc[i][1] != 'Location':
                unit.append(df.iloc[i][0])
                station.append(' '.join(df.iloc[i][1].split(' ')[:-1]))
                line.append(df.iloc[i][1].split(' ')[-1])
        if df.iloc[i][1] != 'Location':
            if df.iloc[i][2] != 'Location':
                if df.iloc[i].isna().sum() == 0:
                    availability.append(df.iloc[i][2])
                if df.iloc[i].isna().sum() == 1:
                    availability.append(df.iloc[i][3].split(' ')[0])
        if df_comment['starts percent'][i] == True:
            if len(comment) > 0:
                comments.append(comment)
                comment = ''
            comment += ' '.join(df_revision['Unnamed: 3'][i].split(' ')[1:])

        if df_comment['continued comment'][i] == True and df_null['Unnamed: 2'][i] == True:
            comment += df_revision['Unnamed: 3'][i]

        if df_comment['full comment'][i] == True:
            if len(comment) > 0:
                comments.append(comment)
                comment = ''
            comments.append(df_revision['Unnamed: 3'][i])

    df_stations = pd.DataFrame(
        {'unit': unit,
         'station': station,
         'line' : line,
         'availability' : availability,
         'comments' : comments
        })
    
    return df_stations

In [12]:
def pdf_transform_v2(start, end, pdf):

    df = tabula.read_pdf(pdf, pages=start)

    for i in range(len(df.columns)):
        df.rename(columns = {df.columns[i]:str(i)}, inplace = True) 

    for i in range(start + 1, end):
        df2 = tabula.read_pdf(pdf, pages=[i])
        for i in range(len(df2.columns)):
            df2.rename(columns = {df2.columns[i]:str(i)}, inplace = True) 

        df = pd.concat([df, df2], axis=0).reset_index(drop = True)

    df.dropna(how = 'all', inplace = True)
    df.reset_index(inplace = True, drop = True)

    unit = []
    station = []
    line = []
    availability = []
    comment = ''
    comments = []

    if len(df.columns) > 4:
        df = df[list(df.columns[:-1])]

    df_revision = df.copy()
    df_null = df.isna()

    df_revision.replace(to_replace=[r"\\t|\\n|\\r", "\t|\n|\r"], value=[" "," "], regex=True, inplace=True)

    df_comment = pd.DataFrame(
        {'full comment': df['3'].str.contains('^(Th).*$'),
         'starts percent': df['3'].str.contains('\d{1,2}\.\d{2}\%'),
         'continued comment': df['3'].str.contains('^[a-zA-SU-Z]*[\s]'),
         'all caps': df['3'].str.contains('^[^a-z]*$'),
         'no spaces': df['3'].str.contains('^[^\s]*$'),
        })

    for i in range(len(df)):
        try:
            if math.isnan(float(df.iloc[i][1])) is True:
                pass
        except:
            if df.iloc[i][1] != 'Location':
                if re.match(string = df.iloc[i][0], pattern = 'E|[SL]\d{3}'):
                    unit.append(df.iloc[i][0])
                station.append(' '.join(df.iloc[i][1].split(' ')[:-1]))
                line.append(df.iloc[i][1].split(' ')[-1])
            if df.iloc[i].isna().sum() == 0:
                if re.match(string = df.iloc[i][2], pattern = '\d{1,2}\.\d{2}\%'):
                    availability.append(df.iloc[i][2])
            if df.iloc[i].isna().sum() == 1:
                if re.match(string = df.iloc[i][3].split(' ')[0], pattern = '\d{1,2}\.\d{2}\%'):
                    availability.append(df.iloc[i][3].split(' ')[0])
            if df_comment['starts percent'][i] == True:
                if len(comment) > 0:
                    comments.append(comment)
                    comment = ''
                comment += ' '.join(df_revision['3'][i].split(' ')[1:])

            if df_comment['continued comment'][i] == True and df_null['2'][i] == True:
                comment += df_revision['3'][i]

            if df_comment['full comment'][i] == True:
                if len(comment) > 0:
                    comments.append(comment)
                    comment = ''
                comments.append(df_revision['3'][i])

    df_stations = pd.DataFrame(
        {'unit': unit,
         'station': station,
         'line' : line,
         'availability' : availability,
         'comments' : comments
        })

    return df_stations

In [78]:
pdf_transform_v2(380, 384, '190923_1000_Transit.pdf').head()

/Users/robblatt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

,unit,station,line,availability,comments
0,EL204,Grand Central-42 St,4567S,72.36%,This elevator was out of service on multiple d...
1,EL119,181 St,A,81.16%,This elevator was out of service from 6/3/19 t...
2,EL224,8 Av,L,83.42%,This elevator was out of service on multiple o...
3,ES104,Gun Hill Rd,25,74.40%,This escalator had multiple outages for lower ...
4,ES105,Gun Hill Rd,25,79.55%,This escalator was out of service multiple tim...

In [79]:
pdf_transform_v2(235, 238, '190520_1030_Transit.pdf').head()

/Users/robblatt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]
/Users/robblatt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

,unit,station,line,availability,comments
0,EL340,Franklin Av,CS,78.96%,This elevator had 2 incidents and it was out o...
1,EL312,Clark St,23,81.47%,This elevator was out of service 8 times due t...
2,ES104,Gun Hill Rd,25,82.89%,This escalator was out of service from 1/7/19 ...
3,ES106,West Farms Sq-E Tremont Av,25,77.55%,This escalator was out of service from 12/28/1...
4,ES108,Intervale Av,25,78.18%,This escalator was out of service from 12/29/1...

In [80]:
pdf_transform_v2(328, 330, '190225_1030_transit-bus.pdf').head()

/Users/robblatt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

ValueError: arrays must all be same length

In [157]:
pdf = '190225_1030_transit-bus.pdf'
start = 328
end = 330

In [158]:
df = tabula.read_pdf(pdf, pages=start)

for i in range(len(df.columns)):
    df.rename(columns = {df.columns[i]:str(i)}, inplace = True) 

for i in range(start + 1, end):
    df2 = tabula.read_pdf(pdf, pages=[i])
    for i in range(len(df2.columns)):
        df2.rename(columns = {df2.columns[i]:str(i)}, inplace = True) 

    df = pd.concat([df, df2], axis=0).reset_index(drop = True)

In [159]:
df.dropna(how = 'all', inplace = True)
df.reset_index(inplace = True, drop = True)

In [216]:
unit = []
station = []
line = []
availability = []
comment = ''
comments = []

if len(df.columns) > 4:
    df = df[list(df.columns[:-1])]

df_revision = df.copy()
df_null = df.isna()

In [217]:
df_revision.replace(to_replace=[r"\\t|\\n|\\r", "\t|\n|\r"], value=[" "," "], regex=True, inplace=True)

df_comment = pd.DataFrame(
    {'full comment': df['3'].str.contains('^(Th).*$'),
     'starts percent': df['3'].str.contains('\d{1,2}\.\d{2}\%'),
     'continued comment': df['3'].str.contains('^[a-zA-SU-Z]*[\s]'),
     'all caps': df['3'].str.contains('^[^a-z]*$'),
     'no spaces': df['3'].str.contains('^[^\s]*$'),
    })

/Users/robblatt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  after removing the cwd from sys.path.

In [218]:
for i in range(len(df)):
    try:
        
        if math.isnan(float(df.iloc[i][1])) is True:
            pass
        
    except:
        
        if df.iloc[i][1] != 'Location':
            if re.match(string = df.iloc[i][0], pattern = 'E|[SL]\d{3}'):
                unit.append(df.iloc[i][0])
            station.append(' '.join(df.iloc[i][1].split(' ')[:-1]))
            line.append(df.iloc[i][1].split(' ')[-1])
            
        if df.iloc[i].isna().sum() == 0:
            if re.match(string = df.iloc[i][2], pattern = '\d{1,2}\.\d{2}\%'):
                availability.append(df.iloc[i][2])
                
        if df.iloc[i].isna().sum() == 1:
            if re.match(string = df.iloc[i][3].split(' ')[0], pattern = '\d{1,2}\.\d{2}\%'):
                availability.append(df.iloc[i][3].split(' ')[0])
                
        if df_comment['starts percent'][i] == True:
            if len(comment) > 0:
                comments.append(comment)
                comment = ''
            comment += ' '.join(df_revision['3'][i].split(' ')[1:])

        if df_comment['full comment'][i] == True and df_null['2'][i] == True:
            comment += df_revision['3'][i]

        if df_comment['full comment'][i] == True and df_null['2'][i] == False:
            if len(comment) > 0:
                comments.append(comment)
                comment = ''
            comments.append(df_revision['3'][i])

        if df_comment['continued comment'][i] == True:
            comment += df_revision['3'][i]
                
if len(comment) > 0:
    comments.append(comment)

In [219]:
len(comments)

17

In [220]:
df_stations = pd.DataFrame(
    {'unit': unit,
     'station': station,
     'line' : line,
     'availability' : availability,
     'comments' : comments
    })

In [221]:
df_stations

,unit,station,line,availability,comments
0,EL120,190 St,A,27.18%,This elevator was out multiple times due to le...
1,EL249,86 St,Q,84.06%,This elevator was out of service from 11/19/18...
2,ES104,Gun Hill Rd,25,83.76%,From 10/1/18 to 12/23/18 the escalator went ou...
3,ES105,Gun Hill Rd,25,83.48%,From 10/1/18 to 12/23/18 the escalator went ou...
4,ES106,West Farms Sq-E Tremont Av,25,79.51%,From 10/1/18 to 12/23/18 the escalator went ou...
5,ES108,Intervale Av,25,69.84%,The escalator was out service from 10/17/2018 ...
6,ES114,161 St-Yankee Stadium,4,69.45%,The escalator was out of service from 10/18/20...
7,ES120,Pelham Bay Park,6,22.72%,The escalator was out of service from 09/01/20...
8,ES305,Court St,R,50.95%,This escalator was out of service from 10/6/18...
9,ES347,Broadway Junction,ACJLZ,84.90%,This escalator was out of service 13 times due...
10,ES349,Smith 9 St,FG,83.91%,This escalator was out of service 12 times due...
11,ES101,125 St,1,82.81%,The escalator was out of service from 10/04/20...
12,ES102,125 St,1,80.27%,The escalator was out of service multiple time...
13,ES118,181 St,A,82.54%,The escalator was out of service from 10/18/20...
14,ES208,Grand Central-42 St,7,84.73%,The escalator went out of service multiple tim...
15,ES217,Times Sq-42 St,7,80.93%,The escalator went out of service multiple tim...
16,ES233,34 St-Herald Sq,BDFM,79.90%,The escalator went out multiple times for hand...

In [94]:
df['3'][7]

'83.76% From 10/1/18 to 12/23/18 the escalator went out of service multiple times for emergency stop button'

In [95]:
df['3'][8]

'activation due to vandalism. From 10/1/18 to 12/23/18 the escalator went out of service multiple times due'

In [96]:
df['3'][9]

'to the comb stop safety device being too sensitive. The comb stop safety device was adjusted; the escalator'

In [97]:
df['3'][10]

'was tested and returned to service.'

In [99]:
comment = ''
comments = []

for i in range(len(df)):
    if df_comment['starts percent'][i] == True:
        if len(comment) > 0:
            comments.append(comment)
            comment = ''
        comment += ' '.join(df_revision['3'][i].split(' ')[1:])

    if df_comment['continued comment'][i] == True and df_null['2'][i] == True:
        comment += df_revision['3'][i]

    if df_comment['full comment'][i] == True and df_null['2'][i] == True:
        comment += df_revision['3'][i]

    if df_comment['full comment'][i] == True:
        if len(comment) > 0:
            comments.append(comment)
            comment = ''
        comments.append(df_revision['3'][i])

In [118]:
df_comment[df_comment['full comment'] == True]

   full comment starts percent continued comment all caps no spaces
2          True          False             False    False     False
3          True          False             False    False     False
32         True          False             False    False     False
41         True          False             False    False     False

In [128]:
df_test = df.loc[7:10]

In [129]:
df_test

,0,1,2,3
7,ES104,Gun Hill Rd 25,NaN,83.76% From 10/1/18 to 12/23/18 the escalator ...
8,NaN,NaN,NaN,activation due to vandalism. From 10/1/18 to 1...
9,NaN,NaN,NaN,to the comb stop safety device being too sensi...
10,NaN,NaN,NaN,was tested and returned to service.

In [212]:
comment = ''
comments = []
g = 0
g_list = []

for i in range(len(df)):
    if df_comment['starts percent'][i] == True:
        if len(comment) > 0:
            comments.append(comment)
            comment = ''
        comment += ' '.join(df_revision['3'][i].split(' ')[1:])
        g += 1
        g_list.append(i)
        print(str(len(comments)) + ' - ' + str(i) + ' - ' + str(g) + ' starts percent')

    if df_comment['full comment'][i] == True and df_null['2'][i] == True:
        comment += df_revision['3'][i]
        print(str(g) + ' continued comment revision')

    if df_comment['full comment'][i] == True and df_null['2'][i] == False:
        if len(comment) > 0:
            comments.append(comment)
            comment = ''
        comments.append(df_revision['3'][i])
        g += 1
        g_list.append(i)
        print(str(len(comments)) + ' - ' + str(i) + ' - ' + str(g) + ' full comment')

    if df_comment['continued comment'][i] == True:
        comment += df_revision['3'][i]
        print(str(g) + ' continued comment')
        
if len(comment) > 0:
    comments.append(comment)

1 - 2 - 1 full comment
2 - 3 - 2 full comment
2 - 7 - 3 starts percent
3 continued comment
3 continued comment
3 continued comment
3 - 11 - 4 starts percent
4 continued comment
4 continued comment
4 continued comment
4 continued comment
4 continued comment
4 - 17 - 5 starts percent
5 continued comment
5 continued comment
5 continued comment
5 - 21 - 6 starts percent
6 continued comment
6 continued comment
6 continued comment
6 - 25 - 7 starts percent
7 continued comment
7 continued comment
7 continued comment
7 continued comment
7 - 31 - 8 starts percent
8 continued comment revision
8 continued comment
8 continued comment
8 continued comment
8 - 38 - 9 starts percent
9 continued comment
9 continued comment
9 continued comment revision
9 continued comment
9 continued comment
9 - 44 - 10 starts percent
10 continued comment
10 - 47 - 11 starts percent
11 continued comment
11 continued comment
11 - 52 - 12 starts percent
12 continued comment
12 continued comment
12 - 57 - 13 starts percent
13 continued comment
13 continued comment
13 continued comment
13 continued comment
13 continued comment
13 continued comment
13 - 64 - 14 starts percent
14 continued comment
14 continued comment
14 continued comment
14 continued comment
14 continued comment
14 - 72 - 15 starts percent
15 continued comment
15 continued comment
15 continued comment
15 - 76 - 16 starts percent
16 continued comment
16 continued comment
16 continued comment
16 continued comment
16 - 81 - 17 starts percent
17 continued comment
17 continued comment
17 continued comment
17 continued comment
17 continued comment
17 continued comment
17 continued comment
17 continued comment
17 continued comment

In [213]:
len(comments)

17

In [193]:
df_comment

   full comment starts percent continued comment all caps no spaces
0         False          False             False    False      True
1           NaN            NaN               NaN      NaN       NaN
2          True          False             False    False     False
3          True          False             False    False     False
4         False          False             False    False     False
5         False          False             False    False      True
6           NaN            NaN               NaN      NaN       NaN
7         False           True             False    False     False
8         False          False              True    False     False
9         False          False              True    False     False
10        False          False              True    False     False
11        False           True             False    False     False
12        False          False              True    False     False
13        False          False              True    False     False
14        False          False              True    False     False
15        False          False              True    False     False
16        False          False              True    False     False
17        False           True             False    False     False
18        False          False              True    False     False
19        False          False              True    False     False
20        False          False              True    False     False
21        False           True             False    False     False
22        False          False              True    False     False
23        False          False              True    False     False
24        False          False              True    False     False
25        False           True             False    False     False
26        False          False             False    False     False
27        False          False              True    False     False
28        False          False              True    False     False
29        False          False              True    False     False
30        False          False              True    False     False
31        False           True             False    False     False
32         True          False             False    False     False
33        False          False             False    False     False
34        False          False              True    False     False
35        False          False              True    False     False
36        False          False              True    False     False
37          NaN            NaN               NaN      NaN       NaN
38        False           True             False    False     False
39        False          False              True    False     False
40        False          False              True    False     False
41         True          False             False    False     False
42        False          False              True    False     False
43        False          False              True    False     False
44        False           True             False    False     False
45        False          False             False    False     False
46        False          False              True    False     False
47        False           True             False    False     False
48        False          False             False    False     False
49        False          False              True    False     False
50        False          False              True    False     False
51          NaN            NaN               NaN      NaN       NaN
52        False           True             False    False     False
53        False          False             False    False     False
54        False          False              True    False     False
55        False          False              True    False     False
56        False          False             False    False     False
57        False           True             False    False     False
58        False          False              True    False     False
59        False          False              True    False     False
60        False          False              True    False     False
61        False          False              True    False     False
62        False          False              True    False     False
63        False          False              True    False     False
64        False           True             False    False     False
65        False          False              True    False     False
66        False          False              True    False     False
67        False          False              True    False     False
68        False          False              True    False     False
69        False          False             False    False     False
70        False          False              True    False     False
71        False          False             False    False     False
72        False           True             False    False     False
73        False          False              True    False     False
74        False          False              True    False     False
75        False          False              True    False     False
76        False           True             False    False     False
77        False          False              True    False     False
78        False          False              True    False     False
79        False          False              True    False     False
80        False          False              True    False     False
81        False           True             False    False     False
82        False          False              True    False     False
83        False          False              True    False     False
84        False          False              True    False     False
85        False          False              True    False     False
86        False          False              True    False     False
87        False          False              True    False     False
88        False          False              True    False     False
89        False          False              True    False     False
90        False          False              True    False     False

In [166]:
g_list

[2, 3, 7, 11, 17, 21, 25, 31, 38, 44, 47, 52, 57, 64, 72, 76, 81]

In [167]:
for i in g_list:
    print(str(i) + ' ' + df_revision['3'][i])

2 This elevator was out multiple times due to leveling issues. The elevator was out of service from 10/16/18 to 12/18/18 for the replacement of the elevator controller. The contractor replaced the elevator controller; the elevator was tested and returned to service. This elevator is in the 2015- 2019 Capital Program for replacement.
3 This elevator was out of service from 11/19/18 to 11/28/18 and from 11/28/18 to 12/1/18 due to a warranty repair of the hydraulic valve body. The hydraulic valve body was replaced and adjusted; the elevator was tested and returned to service.
7 83.76% From 10/1/18 to 12/23/18 the escalator went out of service multiple times for emergency stop button
11 83.48% From 10/1/18 to 12/23/18 the escalator went out of service multiple times for emergency stop button
17 79.51% From 10/1/18 to 12/23/18 the escalator went out of service multiple times for emergency stop button
21 69.84% The escalator was out service from 10/17/2018 to 11/4/2018 due to the comb carriers needing repairs. The
25 69.45% The escalator was out of service from 10/18/2018 to 10/22/2018. All steps and step chain tracks were
31 22.72% The escalator was out of service from 09/01/2018 to 11/23/2018 due to a defective handrail transmission.
38 50.95% This escalator was out of service from 10/6/18 to 11/16/18 due to a rehabilitation effort involving the
44 84.90% This escalator was out of service 13 times due to various issues involving the controller and defective
47 83.91% This escalator was out of service 12 times due to various issues involving the comb stop. Repairs were
52 82.81% The escalator was out of service from 10/04/2018 to 10/6/2018 due to a worn-out handrail and countershaft
57 80.27% The escalator was out of service multiple times from 10/1/2018 to 12/23/2018 due to comb impact/ comb
64 82.54% The escalator was out of service from 10/18/2018 to 10/24/2018 due to a defective microprocessor. The 401
72 84.73% The escalator went out of service multiple times due to the activation of the comb stop and comb impact
76 80.93% The escalator went out of service multiple times due to the activation of the comb stop safety device. The
81 79.90% The escalator went out multiple times for handrail and brake related issues. The escalator was out of

In [174]:
unit

['EL120',
 'EL249',
 'ES104',
 'ES105',
 'ES106',
 'ES108',
 'ES114',
 'ES120',
 'ES305',
 'ES347',
 'ES349',
 'ES101',
 'ES102',
 'ES118',
 'ES208',
 'ES217',
 'ES233']

In [186]:
len(comments)

16

In [181]:
len(unit)

17

In [182]:
len(station)

17

In [183]:
len(availability)

17

In [155]:
df_null

        0      1      2      3
0   False  False  False  False
1   False   True   True   True
2   False  False  False  False
3   False  False  False  False
4   False   True  False  False
5    True   True   True  False
6   False   True   True   True
7   False  False   True  False
8    True   True   True  False
9    True   True   True  False
10   True   True   True  False
11  False  False   True  False
12   True   True   True  False
13   True   True   True  False
14   True   True   True  False
15   True   True   True  False
16   True   True   True  False
17  False  False   True  False
18   True   True   True  False
19   True   True   True  False
20   True   True   True  False
21  False  False   True  False
22   True   True   True  False
23   True   True   True  False
24   True   True   True  False
25  False  False   True  False
26   True   True   True  False
27   True   True   True  False
28   True   True   True  False
29   True   True   True  False
30   True   True   True  False
31  False  False   True  False
32   True   True   True  False
33   True   True   True  False
34   True   True   True  False
35   True   True   True  False
36   True   True   True  False
37  False   True   True   True
38  False  False   True  False
39   True   True   True  False
40   True   True   True  False
41   True   True   True  False
42   True   True   True  False
43   True   True   True  False
44  False  False   True  False
45   True   True   True  False
46   True   True   True  False
47  False  False   True  False
48   True   True   True  False
49   True   True   True  False
50   True   True   True  False
51  False   True   True   True
52  False  False   True  False
53   True   True   True  False
54   True   True   True  False
55   True   True   True  False
56   True   True   True  False
57  False  False   True  False
58   True   True   True  False
59   True   True   True  False
60   True   True   True  False
61   True   True   True  False
62   True   True   True  False
63   True   True   True  False
64  False  False   True  False
65   True   True   True  False
66   True   True   True  False
67   True   True   True  False
68   True   True   True  False
69   True   True   True  False
70   True   True   True  False
71   True   True   True  False
72  False  False   True  False
73   True   True   True  False
74   True   True   True  False
75   True   True   True  False
76  False  False   True  False
77   True   True   True  False
78   True   True   True  False
79   True   True   True  False
80   True   True   True  False
81  False  False   True  False
82   True   True   True  False
83   True   True   True  False
84   True   True   True  False
85   True   True   True  False
86   True   True   True  False
87   True   True   True  False
88   True   True   True  False
89   True   True   True  False
90   True   True   True  False